/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeColor: typeof import('./src/components/codeColor.vue')['default']
    CodeColor_codeMirror: typeof import('./src/components/codeColor_codeMirror.vue')['default']
    CodeColor_dcj: typeof import('./src/components/codeColor_dcj.vue')['default']
    CodeColor_naiveUI: typeof import('./src/components/codeColor_naiveUI.vue')['default']
    GetAPI: typeof import('./src/components/getAPI.vue')['default']
    MenuLeftOne: typeof import('./src/components/menuLeftOne.vue')['default']
    NCode: typeof import('naive-ui')['NCode']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchLog_rightSide: typeof import('./src/components/searchLog_rightSide.vue')['default']
    SearchLog_rightSide_select: typeof import('./src/components/searchLog_rightSide_select.vue')['default']
  }
}
